apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy-deployment
  labels:
    service: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: nzikak/reverseproxy:v2
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"  
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy-service
spec:
  selector:
    service: reverseproxy
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080

